allow keyboard events on shadow root hosts
testing-library/user-event pull request #1235
Opened 2024-09-24 20:59 UTC by mattclough1

**What**:
Resolves #1153 

**Why**:
The current code only allows keyboard entry on elements with a ShadowRoot if the ShadowRoot has a focusable element

**How**:
The `getActiveElement` function previously checked for the existence of a `shadowRoot` on the currently active element, since active elements in a shadow DOM make the host element the active element in the light DOM, but this logic ignored the fact that host elements can also be active elements on their own.

**Checklist**:

- [N/A] Documentation
- [x] Tests
- [x] Ready to be merged

2025-01-30 10:56 UTC, ph-fritsche requested changes
Thanks for contributing to this library. :blue_heart:

2025-01-30 10:56 UTC, ph-fritsche commented on tests/keyboard/index.ts
> +  customElements.define('custom-element', CustomElement)
The element definition should be moved out of the test function to the bottom of the test file because the test should have no side-effect and the custom element will be defined for any tests that might be added below.

Naming it e.g. `focusable-shadow-root` might help someone working on this file and I think inlining the class definition into the `define()` might help if someone decides to refactor the file later.

2025-01-30 10:56 UTC, ph-fritsche commented on tests/keyboard/index.ts
> +  expect(keypressHandler).toHaveBeenCalled()
The element (or the first focusable element child) is automatically focused in `setup` (unless `focus: false` option is set). We can simplify the test case.

```suggestion
  const {user, eventWasFired} = setup(
    '<custom-element tabindex="0"></custom-element>',
  )

  await user.keyboard('[Space]')
  expect(eventWasFired('keypress')).toBe(true)
```

2025-01-30 10:56 UTC, ph-fritsche commented on src/utils/focus/getActiveElement.ts
> +      return activeShadowRootElement
```suggestion
    const activeElementInShadowTree = getActiveElement(activeElement.shadowRoot)
    if (activeElementInShadowTree) {
      return activeElementInShadowTree
```

2025-01-31 16:02 UTC, mattclough1 commented on tests/keyboard/index.ts
> +  customElements.define('custom-element', CustomElement)
The custom element isn't actually focusable by itself, but we add the `tabindex` attribute to it in the test to make it focusable. I'm going to (conditionally for best practice) add a tabindex in the constructor so that this custom element serves this single purpose. Does that make sense?

2025-01-31 16:09 UTC, mattclough1 commented on tests/keyboard/index.ts
> +  customElements.define('custom-element', CustomElement)
Like this:

```suggestion
  customElements.define(
    'focusable-custom-element',
    class FocusableCustomElement extends HTMLElement {
      constructor() {
        super()
        this.attachShadow({mode: 'open'})
      }
    
      connectedCallback() {
        if (!this.hasAttribute('tabindex')) {
          this.setAttribute('tabindex', '0')
        }
      }
    }
  )
```

2025-01-31 17:38 UTC, ph-fritsche commented on tests/keyboard/index.ts
> +  customElements.define('custom-element', CustomElement)
I think either would be okay:
`<custom-element tabindex="0"></custom-element>` or `<focusable-custom-element></focusable-custom-element>`.

Just move it out of the test.

2025-01-31 18:48 UTC, ph-fritsche approved these changes

2025-02-04 21:50 UTC, merged

2025-03-21 11:13 UTC, Artur- commented
Ran into this same issue today. Can we get a release with it?

2025-03-31 19:59 UTC, coder-se commented
Same here, just ran into this issue. Fantastic that it's already solved. Would love a release with it.