Support 'Enter' key press on links
testing-library/user-event pull request #534
Opened 2020-12-28 10:28 UTC by benadamstyles

**What**: in `handleEnter`, there is currently a check for whether the element is clickable, and if it is, it fires a click event on that element. This PR includes anchor tags (with truthy `href` values) in that check.

**Why**: anchor tags are incorrectly missed out of this logic.

**How**: included anchor tags in the `isClickable` util function.

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests
- [ ] Typings
- [ ] Ready to be merged

2021-02-08 12:30 UTC, ph-fritsche commented
`isClickable` is used by `handleSpace` too, but `space` does not trigger a `click` on `Anchor` elements in the browser.
This would introduce a bug there.

I suggest to edit this instead of the util:
https://github.com/testing-library/user-event/blob/287e5b8d0a5c537297b5a338cdd60a476049c375/src/type.js#L582
```js
if (isClickable(currentElement()) || isInstanceofElement(currentElement(), 'HTMLAnchorElement')) {
```

(Maybe slap some comment on `isClickable` (or even change the name) that it only covers clickable *inputs*.)

2021-02-11 19:36 UTC, benadamstyles commented
@ph-fritsche Thanks for the feedback! I think I've addressed everything.

2021-02-11 21:01 UTC, ph-fritsche requested changes

2021-02-12 09:04 UTC, ph-fritsche approved these changes

2021-02-13 11:44 UTC, merged

2021-02-13 11:45 UTC, ph-fritsche commented
@all-contributors add @benadamstyles for code, tests