fix(click): throw an error when trying to click with pointer-events set to none
testing-library/user-event pull request #647
Opened 2021-04-12 16:05 UTC by vicrep

**What**:

As discussed here: https://github.com/testing-library/user-event/issues/639#issuecomment-816924740 , the new behaviour which was recently added to prevent clicks from being emitted when pointer-events are set to `none` had the side-effect of silently no-oping when this was the case, making it:
- non-trivial to figure out why your next assertion failed, given the click 'executed' in the PoV of the test
- hard to work around libraries which set these pointer events while animating

I've added this behaviour to both the click and double-click.

**Why**:

This change follows the paradigm that testing-library provides for selectors, where `getBy` will throw an error if the element doesn't exist. Similarly, trying to click something which is not clickable should also throw an error, as this is an action which cannot be performed by a real user. Some other testing frameworks, such as Cypress, follow similar behaviour of failing when trying to click non-clickable elements.

This also makes dealing with animating elements which might set their pointer events to `none` way more straightforward, using the `waitFor` utility:

```ts
await waitFor(() => userEvent.click(screen.getByText("OK")))
```

**Checklist**:

- [ ] Documentation
- [x] Tests
- [x] Typings
- [x] Ready to be merged

2021-04-13 07:28 UTC, ph-fritsche requested changes

2021-04-13 07:28 UTC, ph-fritsche commented on README.md
> +with `user-events` being set to `"none"` (i.e. unclickable) will throw an error.
```suggestion
with `pointer-events` being set to `"none"` (i.e. unclickable) will throw an error.
```

Thanks for spotting the typo.
While we're at it, let's fix the property name to.

2021-04-13 07:35 UTC, ph-fritsche requested changes
Thanks for your contribution. :heart:

2021-04-13 07:35 UTC, ph-fritsche commented on README.md
> +with `user-events` being set to `"none"` (i.e. unclickable) will throw an error.
```suggestion
with `pointer-events` being set to `"none"` (i.e. unclickable) will throw an error.
```

2021-04-13 07:35 UTC, ph-fritsche commented on src/click.ts
> +      'unable to click element as it or a parent has pointer-events set to "none".',
```suggestion
      'unable to click element as it has or inherits pointer-events set to "none".',
```

2021-04-13 07:35 UTC, ph-fritsche commented on src/click.ts
> +      'unable to double-click element as it or a parent has pointer-events set to "none".',
```suggestion
      'unable to double-click element as it has or inherits pointer-events set to "none".',
```

2021-04-13 07:37 UTC, ph-fritsche commented
We probably should throw the same error on `userEvent.hover` and `userEvent.unhover`

2021-04-13 14:32 UTC, vicrep commented
@ph-fritsche I actually considered doing it for hover too, but wasn't sure if out of scope for this PR. Given that hovers usually provide side-effects and aren't usually explicit actions, I'm not sure if we should error when hovering over something that's disabled. 

FWIW, I find that Cypress has very sensible assertions they make on their commands to simulate user behaviour (such as, [failing when trying to click a non-clickable element](https://docs.cypress.io/api/commands/click#Assertions)) and this is the inspiration I used for this PR. Interestingly, `hover` is [basically the only user 'event' they don't provide a command for](https://docs.cypress.io/api/commands/hover), due to how non-deterministic its behaviour can be depending on implementation. This further added to my uncertainty about adding this to the PR.

What do you think? I'd be happy to add it to this PR, or to propose it as a future (or separate) improvement.

2021-04-13 14:32 UTC, vicrep commented on README.md
> +with `user-events` being set to `"none"` (i.e. unclickable) will throw an error.
Good catch 🙈

2021-04-14 07:35 UTC, ph-fritsche commented
@vicrep I think users calling `userEvent.hover` expect a `mouseover` to be dispatched. So the same logic as for the `click` applies. We don't have layout in jsdom so we could not determine the elements the pointer events would fall through to.

2021-04-14 17:31 UTC, vicrep commented
@ph-fritsche makes sense, I've added the same behaviour to hover/un-hover 👍 

Please let me know if there's anything else you need from me to merge this :)

2021-04-14 21:51 UTC, ph-fritsche approved these changes
Looks good to me :)

2021-04-14 22:03 UTC, merged

2021-04-14 22:59 UTC, ph-fritsche commented
@all-contributors add @vicrep code