Relaxing element type definitions to HTMLElement
testing-library/user-event pull request #649
Opened 2021-04-12 21:43 UTC by GreenGremlin

Fixes #648

**What**: Relaxing element argument types to match the type returned by react-testing-library queries.

**Why**: 

To allow user-event functions to be used with RTS queries without type casting.

**How**:

See changes

**Checklist**:

- [ ] Documentation N/A
- [x] Tests
- [x] Typings
- [x] Ready to be merged

2021-04-12 21:48 UTC, GreenGremlin commented on src/__tests__/upload.js
> +test('should give error if we are trying to call upload on an invalid element', () => {
This is pretty much just a copy / paste from the existing test for paste.

2021-04-14 23:01 UTC, ph-fritsche requested changes
Thanks for taking the time to contribute. :heart:

2021-04-16 20:37 UTC, GreenGremlin commented on src/paste.ts
> +      element instanceof HTMLTextAreaElement
I've updated all `instanceof` checks to use `isElementType`

2021-04-16 20:38 UTC, GreenGremlin commented on src/paste.ts
> +    typeof element.value === 'undefined'
I've removed this check

2021-04-16 20:39 UTC, GreenGremlin commented on src/upload.ts
> +    )
Done

2021-04-16 20:39 UTC, GreenGremlin commented on src/upload.ts
> +      element instanceof HTMLInputElement || element instanceof HTMLLabelElement
Done

2021-04-16 20:39 UTC, GreenGremlin commented on src/paste.ts
>        `the current element is of type ${element.tagName} and doesn't have a valid value`,
I've updated the error message to `the current element is of type ${element.tagName} and does not accept file uploads`

2021-04-18 08:39 UTC, ph-fritsche commented on src/paste.ts
> +      element instanceof HTMLTextAreaElement
@GreenGremlin You need to push your changes to https://github.com/GreenGremlin/user-event/tree/type-fixes

2021-04-18 18:08 UTC, GreenGremlin commented on src/paste.ts
> +      element instanceof HTMLTextAreaElement
Sorry, they're pushed now.

2021-04-18 19:58 UTC, ph-fritsche requested changes
I've opened a PR with code suggestions at https://github.com/GreenGremlin/user-event/pull/1

2021-04-18 22:22 UTC, GreenGremlin commented
@ph-fritsche thanks! I've merged your changes.

2021-04-19 07:26 UTC, ph-fritsche approved these changes

2021-04-19 11:26 UTC, merged

2021-04-19 11:27 UTC, ph-fritsche commented
@all-contributors add @GreenGremlin code

2021-04-19 16:43 UTC, GreenGremlin commented
Thank you!